### ISSUE TITLE
authentication app

### ISSUE THREAD

**Issue by seokulee** [42seoul-ft-transcendence/ft_transcendence#6]
# TODO
- [x] 42 OAuth로 로그인
- [ ] 2FA (email) 인증
  - [x] 개발 환경 이메일 설정 -> Email이 콘솔에 Log
  - [ ] 배포 환경 이메일 (Real email) 확인하기
  - [x] Toggle 가능
- [x] JWT 사용하기

# API 명세서
## 1. `GET /api/auth/42/login/`

- **설명**: 42 OAuth 로그인 페이지로 리디렉션합니다.
- **HTTP 메서드**: `GET`
- **요청 파라미터**: 없음
- **응답**: `302 Found` - 42 OAuth 로그인 페이지로 리디렉션

---

## 2. `GET /api/auth/42/callback/`

- **설명**: 42 OAuth 인증 후 콜백 URL로, 사용자 정보 요청 및 JWT 발급을 담당합니다.
- **HTTP 메서드**: `GET`
- **요청 파라미터**:
    - `code` (필수): `string` - 42 OAuth로부터 받은 인증 코드
- **응답**:
    - **2FA 활성화 사용자의 경우**
        - **Status**: `200 OK`
        - **Response**: 
		```json
        {
           "message": "2FA code sent to your email. Please verify to complete login.",
           "username": "your_username" 
         }
		```
    - **2FA 비활성화 사용자의 경우**
        - **Status**: `200 OK`
        - **Response**: 
        ```json
	    {
          "refresh": "your_refresh_token",
          "access": "your_access_token",
          "username": "user_username",
          "email": "user_email",
          "avatar": "avatar_url" 
	    }     
		```
            

---

#### 3. `POST /api/auth/2fa/verify/`

- **설명**: 이메일로 전송된 2FA OTP 코드를 검증하고, 성공 시 JWT 발급
- **HTTP 메서드**: `POST`
- **요청 파라미터**:
    - **Body**:
        - `username` (필수): `string` - 사용자 이름
        - `otp_code` (필수): `string` - 이메일로 전송된 2FA OTP 코드
- **응답**:
    - **성공 시**
        - **Status**: `200 OK`
        - **Response**:
		```json
	    {
          "refresh": "your_refresh_token",
          "access": "your_access_token"
	    }     
		```
    - **OTP 코드 오류 시**
        - **Status**: `400 Bad Request`
        - **Response**:
        ```json
	    {
			"error": "Invalid OTP code."
		}
		```

---

#### 4. `POST /api/auth/2fa/toggle/`

- **설명**: 2FA (Two-Factor Authentication)를 활성화하거나 비활성화
- **HTTP 메서드**: `POST`
- **요청 헤더**:
    - `Authorization`: `Bearer <access_token>` - 사용자의 인증 토큰
- **요청 파라미터**:
    - **Body**:
        - `enable_2fa` (선택): `boolean` - `true`이면 2FA 활성화, `false`이면 비활성화 (기본값: `true`)
- **응답**:
    - **Status**: `200 OK`
    - **Response**:
    ```json
    {
      "message": "2FA enabled successfully."
    }
	```
    - **비활성화 시 응답**
	```json
	{
	  "message": "2FA disabled successfully."
	}
	```
